### ISSUE TITLE
Refactor database structure - prisma model

### ISSUE THREAD

**Issue by PhucHoangVan** [MediServe-Team/Upgrade_Server#1]
- Cập nhật model Prisma Typeorm dựa trên Database mới

**Comment by vfa-phuchv** [comment]
Tách riêng table **permission** và loại bỏ field permit_list trong table **user** để đạt NF1
![image](https://github.com/MediServe-Team/Upgrade_Server/assets/141104806/7ff3ffc0-80fe-4d3e-bc25-c99e819b6932)

**Comment by vfa-phuchv** [comment]
Gộp các table liên quan đến **product** và **medicine** thành 1 table **item** duy nhất
![image](https://github.com/MediServe-Team/Upgrade_Server/assets/141104806/9929b611-0eb3-40f7-aaa2-4e27fe566b29)


![image](https://github.com/MediServe-Team/Upgrade_Server/assets/141104806/a69c6f02-db17-4a22-bcbc-8d98e5f6e852)

**Comment by vfa-phuchv** [comment]
Tạo thêm table **medicine_guide_sell** để xử lý bán thuốc theo liều (thuốc được dùng để tạo liều bán được lấy trực tiếp từ kho)
![image](https://github.com/MediServe-Team/Upgrade_Server/assets/141104806/901859ea-b23f-41d8-9261-2e68f09c0281)

**Comment by vfa-phuchv** [comment]
comment
